markdown: kramdown
kramdown:
   auto_ids: true
   parse_block_html: true
# theme: jekyll-theme-cayman
# Google Analytics
google_analytics: UA-41542768-4
plugins:
  - jekyll-seo-tag
title: "SSTuino Official Webpage"
description: "SSTuino is an easy to use Wi-Fi enabled microcontroller, designed and fabricated by SST Alumni. Users can write programs to connect or control things over the Internet."
url: "https://d3lta-v.github.io/SSTuino/" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap